apiVersion: autoscaling/v1
kind: HorizontalPodAutoScaler
metadata:
  name: autoscale
  namespace: nodeapp
spec:
  scaleTargetRef:
    kind: Deployment
    name: my-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
